worker_processes auto;

error_log /var/log/angie/error.log info;

events {
  worker_connections 1024;
}

http {
  server {
    listen 443 ssl;

    server_name example.com www.example.com;
    acme example;

    ssl_certificate $acme_cert_example;
    ssl_certificate_key $acme_cert_key_example;
  }
}

http {
  resolver 127.0.0.53;

  acme_client example https://acme-v02.api.letsencrypt.org/directory challenge=dns

  server {
    listen 443 ssl;

    server_name example.com *.example.com
    acme example;

    ssl_certificate $acme_cert_example;
    ssl_certificate_key $acme_cert_key_example;
  }
}

http {
  resolver 127.0.0.53;

  acme_client example https://acme-v02.api.letsencrypt.org/directory challenge=http;

  server {
    listen 80; # required port for the ACME HTTP challenge
    listen 443 ssl;

    server_name example.com www.example.com;
    acme example;

    ssl_certificate $acme_cert_example;
    ssl_certificate_key $acme_cert_key_example;
  }
}

http {
  resolver 127.0.0.53;

  acme_client example https://acme-v02.api.letsencrypt.org/directory challenge=alpn

  server {
    listen 443 ssl;

    server_name example.com *.example.com
    acme example;

    ssl_certificate $acme_cert_example;
    ssl_certificate_key $acme_cert_key_example;
  }
}