user www www;

load_module modules/ngx_mail_module.so;

include mime.types;
include vhosts/*.conf;

# worker_processes 2;
# worker_cpu_affinity 0101 1010
worker_processes auto;
worker_cpu_affinity auto;

error_log /var/log/error.log info;

env MALLOC_OPTIONS;
env PERL5LIB=/data/site/modules;
env OPENSSL_ALLOW_PROXY_CERTS=1;

ssl_object_cache_inheritable on;

events {
  worker_aio_requests 32;
  worker_connections 1024;

  accept_mutex on;
  accept_mutex_delay 500ms;

  debug_connection 127.0.0.1;
  debug_connection localhost;
  debug_connection 192.0.2.0/24;
  debug_connection ::1;
  debug_connection 2001:0db8::/32;
  debug_connection unix:;
}

http {
  server {
    ssl_certificate example.com.crt
    ssl_certificate_key example.com.key
  }
}
